# Generated by Django 3.1.3 on 2020-11-12 16:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201112_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clothing_sizes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('xs', 'X-Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'X-Large')], max_length=11, null=True),
        ),
    ]
